/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simpleapp;

public class App {


    public String getGreeting() {
        return "Hello World!";
    }

    public String getAnotherGreeting() {
        return "Greetings!";
    }

    public static void main(String[] args) {
        Greeting greeting = new Greeting();
        System.out.println(greeting.getGreeting());
        System.out.println(greeting.getAnotherGreeting());
    }
}
