/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simpleapp;

public class Greeting {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getAnotherGreeting() {
        return "Greetings!";
    }

}
